### ISSUE TITLE
Queries are not executed

### ISSUE THREAD

**Issue by amouhoub** [AKSW/AutoSPARQL#32]
Hello
I have successfully managed to run AutoSPARQL on my machine.
The mail adress in the readme ```http://localhost:8080/``` gives an html page with the following error message (But this is not my issue)
```
Error 404 - Not Found.
No context on this server matched or handled this request.
Contexts known to this server are:
```
I could however get the app running on ```http://localhost:8080/autosparql-lite/.```
However, when I choose a query from those suggested , eg:films starring Brad Pitt on dbpedia, the app says " Running... " and stays idle forever.
I checked the terminal, and found the following error message , Any clues please ???
```
Running template generation...
Tagged input: films/NNS starring/VBG Brad/NNP Pitt/NNP
Preprocessed: films/NNS starring/VBG brad_pitt/NNP
>>> DUDE:
<x0,l1,<<e,t>,t>, [l1:[x0 | SLOT_films(x0)], l3:[ | SLOT_starring(x0,y)], l2:[y | ]], [], [l2=l1, l1=l3][SLOT_films: CLASS {films}, SLOT_starring: SYMPROPERTY {starring}, y: RESOURCE {brad pitt}]>

>>> DRS:
l2:[y,x0 | SLOT_starring(x0,y),SLOT_films(x0)]
SLOT_films: CLASS {films}
SLOT_starring: SYMPROPERTY {starring}
y: RESOURCE {brad pitt}
>>> DUDE:
<x0,l1,<<e,t>,t>, [l1:[x0 | SLOT_films(x0)], l3:[ | empty(x0,y)], l2:[y | ]], [], [l2=l1, l1=l3][SLOT_films: CLASS {films}, y: RESOURCE {brad pitt}]>

>>> DRS:
l2:[y,x0 | empty(x0,y),SLOT_films(x0)]
SLOT_films: CLASS {films}
y: RESOURCE {brad pitt}
>>> DUDE:
<x,l1,<<e,t>,t>, [l1:[x | SLOT_films(x),equal(x,y)], l2:[y | ], l4:[ | SLOT_description(y,y0),regex(y0,'starring')]], [], [l2=l1, l2=l4][SLOT_films: CLASS {films}, y: RESOURCE {brad pitt}, SLOT_description: DATATYPEPROPERTY {description}]>

>>> DRS:
l2:[y | SLOT_films(y),regex(y0,'starring'),SLOT_description(y,y0)]
SLOT_films: CLASS {films}
y: RESOURCE {brad pitt}
SLOT_description: DATATYPEPROPERTY {description}
Generated 3 templates:
>> QUERY: SELECT ?y0 { ?y ?p1 ?y0. ?y rdf:type ?p0. FILTER(regex(?y0,'starring','i')). } 
>> SLOTS: y: RESOURCE {brad pitt}p0: CLASS {films}p1: DATATYPEPROPERTY {description}
>> QUERY: SELECT ?x0 { ?x0 ?p0 ?y. ?x0 rdf:type ?p1. } 
>> SLOTS: y: RESOURCE {brad pitt}p0: SYMPROPERTY {starring}p1: CLASS {films}
>> QUERY: SELECT ?x0 { ?y ?p0 ?x0. } 
>> SLOTS: y: RESOURCE {brad pitt}p0: PROPERTY {films}
Running entity disambiguation...
Found 3 entities for slot y: RESOURCE {brad pitt}: [http://dbpedia.org/resource/Brad_Pitt_(boxer)(Brad_Pitt_(boxer)), http://dbpedia.org/resource/Brad_Pitt(Brad_Pitt), http://dbpedia.org/resource/Brad_Pitt_filmography(Brad_Pitt_filmography)]
Found 2 entities for slot p0: CLASS {films}: [http://dbpedia.org/ontology/Film(Film), http://dbpedia.org/ontology/FilmFestival(FilmFestival)]
Found 0 entities for slot p1: DATATYPEPROPERTY {description}: []
Found 3 entities for slot y: RESOURCE {brad pitt}: [http://dbpedia.org/resource/Brad_Pitt_(boxer)(Brad_Pitt_(boxer)), http://dbpedia.org/resource/Brad_Pitt(Brad_Pitt), http://dbpedia.org/resource/Brad_Pitt_filmography(Brad_Pitt_filmography)]
Found 2 entities for slot p0: SYMPROPERTY {starring}: [http://dbpedia.org/ontology/starRating(starRating), http://dbpedia.org/ontology/starring(starring)]
Found 2 entities for slot p1: CLASS {films}: [http://dbpedia.org/ontology/Film(Film), http://dbpedia.org/ontology/FilmFestival(FilmFestival)]
Found 3 entities for slot y: RESOURCE {brad pitt}: [http://dbpedia.org/resource/Brad_Pitt_(boxer)(Brad_Pitt_(boxer)), http://dbpedia.org/resource/Brad_Pitt(Brad_Pitt), http://dbpedia.org/resource/Brad_Pitt_filmography(Brad_Pitt_filmography)]
Found 9 entities for slot p0: PROPERTY {films}: [http://dbpedia.org/ontology/filmAudioType(filmAudioType), http://dbpedia.org/ontology/film(film), http://dbpedia.org/ontology/openingFilm(openingFilm), http://dbpedia.org/ontology/polishFilmAward(polishFilmAward), http://dbpedia.org/ontology/filmColourType(filmColourType), http://dbpedia.org/ontology/nationalFilmAward(nationalFilmAward), http://dbpedia.org/ontology/closingFilm(closingFilm), http://dbpedia.org/ontology/starring(starring), http://dbpedia.org/ontology/filmFareAward(filmFareAward)]
Running template instantiation...
Running ranking...

Exception in thread "Thread-48" java.lang.RuntimeException: connection could not be initialized.
	at org.aksw.autosparql.commons.metric.SPARQLEndpointMetrics.getDefaultReadOnlyConnection(SPARQLEndpointMetrics.java:98)
	at org.aksw.autosparql.commons.metric.SPARQLEndpointMetrics.getDbpediaMetrics(SPARQLEndpointMetrics.java:68)
	at org.aksw.autosparql.tbsl.algorithm.learning.ranking.SimpleRankingComputation.createFeatureExtractors(SimpleRankingComputation.java:131)
	at org.aksw.autosparql.tbsl.algorithm.learning.ranking.SimpleRankingComputation.computeRanking(SimpleRankingComputation.java:78)
	at org.aksw.autosparql.tbsl.algorithm.learning.TBSL.answerQuestion(TBSL.java:198)
	at org.aksw.autosparql.tbsl.algorithm.learning.TBSL.answerQuestion(TBSL.java:156)
	at org.aksw.autosparql.tbsl.gui.vaadin.TBSLManager.answerQuestion(TBSLManager.java:340)
	at org.aksw.autosparql.tbsl.gui.vaadin.view.MainView$11.run(MainView.java:504)
	at java.lang.Thread.run(Thread.java:744)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1137)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:356)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2504)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2541)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2323)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:832)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:408)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:417)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:344)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at org.aksw.autosparql.commons.metric.SPARQLEndpointMetrics.getDefaultReadOnlyConnection(SPARQLEndpointMetrics.java:94)
	... 8 more
Caused by: java.net.NoRouteToHostException: No route to host
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at java.net.Socket.<init>(Socket.java:425)
	at java.net.Socket.<init>(Socket.java:241)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:258)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:306)
	... 23 more
```

**Comment by KonradHoeffner** [comment]
AutoSPARQL is a research prototype that is not maintained anymore and does not work correctly anymore due to changing snapshot dependencies and external services. If you want to get it to run again, you need to debug the source code. If you chose to take this route we would be delighted if you could share your fixes via a pull request.
