### ISSUE TITLE
How to build when I am behind proxy?

### ISSUE THREAD

**Issue by abmjunaed** [AKSW/AutoSPARQL#33]
Hi,
I am using proxy in my office to access internet.
**In AutoSPARQL\commons\src\main\java\org\aksw\autosparql\commons\metric\SPARQLEndpointMetrics.javaSPARQLEndpointMetrics.java, there is**
*String dbHost = "[2001:638:902:2010:0:168:35:119]"*; 
Is it a mac address?
I think I have to tell the JDBC connector to go through the proxy server in this file, but how?

When I do "mvn install -N" in "commons" folder, I get following errors in command prompt:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running LoggerTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.117 sec - in LoggerTest
Running org.aksw.autosparql.commons.index.LemmatizedIndexTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.039 sec - in org.aksw.autosparql.commons.index.LemmatizedIndexTest
Running org.aksw.autosparql.commons.metric.DatabaseBackedSPARQLEndpointMetricsTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.749 sec <<< FAILURE! - in org.aksw.autosparql.commons.metric.DatabaseBackedSPARQLEndpointMetricsTest
testPmiMetric(org.aksw.autosparql.commons.metric.DatabaseBackedSPARQLEndpointMetricsTest)  Time elapsed: 2.749 sec  <<< ERROR!
java.lang.RuntimeException: connection could not be initialized.
        at com.mysql.jdbc.NonRegisteringDriver.parseHostPortPair(NonRegisteringDriver.java:216)
        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2487)
        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2541)
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2323)
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:832)
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:408)
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:417)
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:344)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:208)
        at org.aksw.autosparql.commons.metric.SPARQLEndpointMetrics.getDefaultReadOnlyConnection(SPARQLEndpointMetrics.java:119)
        at org.aksw.autosparql.commons.metric.SPARQLEndpointMetrics.getDbpediaMetrics(SPARQLEndpointMetrics.java:69)
        at org.aksw.autosparql.commons.metric.DatabaseBackedSPARQLEndpointMetricsTest.testPmiMetric(DatabaseBackedSPARQLEndpointMetricsTest.java:32)

Running org.aksw.autosparql.commons.nlp.pos.StanfordPartOfSpeechTaggerTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.369 sec - in org.aksw.autosparql.commons.nlp.pos.StanfordPartOfSpeechTaggerTest
Running org.aksw.autosparql.commons.nlp.wordnet.WordNetTest
1445334923672 - Error on direct access in verb data file: check CR/LF endings
1445334924622 - Error on direct access in adjective data file: check CR/LF endings
1445334924624 - Error on direct access in noun data file: check CR/LF endings
1445334924626 - Error on direct access in adverb data file: check CR/LF endings
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.994 sec - in org.aksw.autosparql.commons.nlp.wordnet.WordNetTest
Running org.aksw.autosparql.commons.nlp.wordnet.WordNetUnpackerTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0 sec <<< FAILURE! - in org.aksw.autosparql.commons.nlp.wordnet.WordNetUnpackerTest
testGetUnpackedWordNetDir(org.aksw.autosparql.commons.nlp.wordnet.WordNetUnpackerTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError:
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.assertTrue(Assert.java:43)
        at org.junit.Assert.assertTrue(Assert.java:54)
        at org.aksw.autosparql.commons.nlp.wordnet.WordNetUnpackerTest.testGetUnpackedWordNetDir(WordNetUnpackerTest.java:15)

Running org.aksw.autosparql.commons.uri.UriDisambiguationTest
Tests run: 3, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.057 sec <<< FAILURE! - in org.aksw.autosparql.commons.uri.UriDisambiguationTest
testGetUriListOfResourceStringString(org.aksw.autosparql.commons.uri.UriDisambiguationTest)  Time elapsed: 0.055 sec  <<< ERROR!
java.lang.RuntimeException: exception with query:
q=surfaceForms%3A%22Leipzig%22&sort=disambiguationScore+desc&fl=surfaceForms%2Curi%2Clabel%2Ccomment%2Ctypes%2CdbpediaUri%2CdisambiguationScore&rows=100
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:907)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1302)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1255)
        at java.net.InetAddress.getAllByName(InetAddress.java:1171)
        at java.net.InetAddress.getAllByName(InetAddress.java:1105)
        at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.resolveHostname(DefaultClientConnectionOperator.java:278)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:162)
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:643)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
        at org.apache.solr.client.solrj.impl.HttpSolrServer.executeMethod(HttpSolrServer.java:448)
        at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:210)
        at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:206)
        at org.apache.solr.client.solrj.request.QueryRequest.process(QueryRequest.java:91)
        at org.apache.solr.client.solrj.SolrServer.query(SolrServer.java:301)
        at org.aksw.autosparql.commons.uri.UriDisambiguation.query(UriDisambiguation.java:188)
        at org.aksw.autosparql.commons.uri.UriDisambiguation.getUriCandidates(UriDisambiguation.java:152)
        at org.aksw.autosparql.commons.uri.UriDisambiguationTest.testGetUriListOfResourceStringString(UriDisambiguationTest.java:19)

testGetUriCandidates(org.aksw.autosparql.commons.uri.UriDisambiguationTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.RuntimeException: exception with query:
q=surfaceForms%3A%22Leipzig%22&sort=disambiguationScore+desc&fl=surfaceForms%2Curi%2Clabel%2Ccomment%2Ctypes%2CdbpediaUri%2CdisambiguationScore&rows=100
        at java.net.InetAddress.getAllByName0(InetAddress.java:1259)
        at java.net.InetAddress.getAllByName(InetAddress.java:1171)
        at java.net.InetAddress.getAllByName(InetAddress.java:1105)
        at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.resolveHostname(DefaultClientConnectionOperator.java:278)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:162)
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:643)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
        at org.apache.solr.client.solrj.impl.HttpSolrServer.executeMethod(HttpSolrServer.java:448)
        at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:210)
        at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:206)
        at org.apache.solr.client.solrj.request.QueryRequest.process(QueryRequest.java:91)
        at org.apache.solr.client.solrj.SolrServer.query(SolrServer.java:301)
        at org.aksw.autosparql.commons.uri.UriDisambiguation.query(UriDisambiguation.java:188)
        at org.aksw.autosparql.commons.uri.UriDisambiguation.getUriCandidates(UriDisambiguation.java:152)
        at org.aksw.autosparql.commons.uri.UriDisambiguationTest.testGetUriCandidates(UriDisambiguationTest.java:12)


Results :

Failed tests:
  WordNetUnpackerTest.testGetUnpackedWordNetDir:15

Tests in error:
  DatabaseBackedSPARQLEndpointMetricsTest.testPmiMetric:32 ▒ Runtime connection ...
  UriDisambiguationTest.testGetUriListOfResourceStringString:19 ▒ Runtime except...
  UriDisambiguationTest.testGetUriCandidates:12 ▒ Runtime exception with query:
...



```

**Comment by KonradHoeffner** [comment]
[2001:638:902:2010:0:168:35:119] is an IPv6 address, so your internet connection needs to support that.
