### ISSUE TITLE
Unable to run main file in tbsl project

### ISSUE THREAD

**Issue by suryahub** [AKSW/AutoSPARQL#36]
Hi,
I cloned OpenQA from the below repository(from developer branch which comes as default when the page loads. https://github.com/AKSW/openqa I build the entire project and when i tried to run the Main.java file in the tbsl project in org.aksw.openqa.component.answerformulation.interpreter.impl package i get the following exception.

String question = "Which caves have more than 3 entrances";
09:23:28,989 WordNetUnpacker - file exists already, skipped: /tmp/wordnet178558556719/noun.exc
09:23:28,992 WordNetUnpacker - file exists already, skipped: /tmp/wordnet178558556719/frames.vrb
09:23:28,993 WordNetUnpacker - file exists already, skipped: /tmp/wordnet178558556719/data.noun
09:23:28,993 WordNetUnpacker - file exists already, skipped: /tmp/wordnet178558556719/verb.Framestext
09:23:28,993 WordNetUnpacker - file exists already, skipped: /tmp/wordnet178558556719/verb.exc
09:23:28,993 WordNetUnpacker - file exists already, skipped: /tmp/wordnet178558556719/data.adv
09:23:28,994 WordNetUnpacker - file exists already, skipped: /tmp/wordnet178558556719/cntlist.rev
09:23:28,994 WordNetUnpacker - file exists already, skipped: /tmp/wordnet178558556719/Makefile
09:23:28,994 WordNetUnpacker - file exists already, skipped: /tmp/wordnet178558556719/lexnames
09:23:28,994 WordNetUnpacker - file exists already, skipped: /tmp/wordnet178558556719/sentidx.vrb
09:23:28,994 WordNetUnpacker - file exists already, skipped: /tmp/wordnet178558556719/adj.exc
09:23:28,994 WordNetUnpacker - file exists already, skipped: /tmp/wordnet178558556719/cntlist
09:23:28,995 WordNetUnpacker - file exists already, skipped: /tmp/wordnet178558556719/adv.exc
09:23:28,995 WordNetUnpacker - file exists already, skipped: /tmp/wordnet178558556719/Makefile.in
09:23:28,995 WordNetUnpacker - file exists already, skipped: /tmp/wordnet178558556719/index.verb
09:23:28,995 WordNetUnpacker - file exists already, skipped: /tmp/wordnet178558556719/index.adv
09:23:28,995 WordNetUnpacker - file exists already, skipped: /tmp/wordnet178558556719/Makefile.am
09:23:28,996 WordNetUnpacker - file exists already, skipped: /tmp/wordnet178558556719/sents.vrb
09:23:28,996 WordNetUnpacker - file exists already, skipped: /tmp/wordnet178558556719/index.sense
09:23:28,996 WordNetUnpacker - file exists already, skipped: /tmp/wordnet178558556719/data.adj
09:23:28,996 WordNetUnpacker - file exists already, skipped: /tmp/wordnet178558556719/index.adj
09:23:28,996 WordNetUnpacker - file exists already, skipped: /tmp/wordnet178558556719/data.verb
09:23:28,997 WordNetUnpacker - file exists already, skipped: /tmp/wordnet178558556719/log.grind.3.0
09:23:28,997 WordNetUnpacker - file exists already, skipped: /tmp/wordnet178558556719/index.noun
org.json.JSONException: A JSONObject text must begin with '{' at character 1
	at org.json.JSONTokener.syntaxError(JSONTokener.java:410)
	at org.json.JSONObject.<init>(JSONObject.java:179)
	at org.json.JSONObject.<init>(JSONObject.java:402)
	at org.aksw.autosparql.commons.nlp.ner.DBpediaSpotlightNER.getNamedEntitites(DBpediaSpotlightNER.java:54)
	at org.aksw.autosparql.tbsl.algorithm.ltag.parser.Preprocessor.findNEs(Preprocessor.java:306)
	at org.aksw.autosparql.tbsl.algorithm.templator.Templator.buildTemplates(Templator.java:173)
	at org.aksw.autosparql.tbsl.algorithm.learning.TBSL.answerQuestion(TBSL.java:164)
	at org.aksw.autosparql.tbsl.algorithm.learning.TBSL.answerQuestion(TBSL.java:156)
	at org.aksw.openqa.component.answerformulation.interpreter.impl.Main.main(Main.java:26)
Exception in thread "main" org.apache.solr.client.solrj.impl.HttpSolrServer$RemoteSolrException: Expected content type application/octet-stream but got text/html; charset=UTF-8. <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>404: Resource not found</title>
<style type="text/css">
body {
    font-family: sans-serif;
    line-height: 1.5;
    background-color: #eff9ff;
}

h1 {
    font-size: 100%
}
</style>
</head>
<body>
<h1>Resource not found</h1>
<p>
The resource <code>http://linkedspending.aksw.org/solr/en_dbpedia_classes/select?q=label%3A%22caves%22%5E2+&rows=10&fl=uri%2Cscore&wt=javabin&version=2</code> you are trying to reach does not exist.<br />
Do you want to <a href="http://linkedspending.aksw.org/resource/new/?r=http%3A%2F%2Flinkedspending.aksw.org%2Fsolr%2Fen_dbpedia_classes%2Fselect%3Fq%3Dlabel%253A%2522caves%2522%255E2%2B%26rows%3D10%26fl%3Duri%252Cscore%26wt%3Djavabin%26version%3D2">create it</a>?<br />
Otherwise, try to <a href"http://linkedspending.aksw.org/">go back</a>.
</p>
</body>
</html>

	at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:455)
	at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:197)
	at org.apache.solr.client.solrj.request.QueryRequest.process(QueryRequest.java:90)
	at org.apache.solr.client.solrj.SolrServer.query(SolrServer.java:301)
	at org.aksw.rdfindex.SOLRIndex.getResourcesWithScores(SOLRIndex.java:82)
	at org.aksw.autosparql.commons.search.FilteredIndex.getResourcesWithScores(FilteredIndex.java:18)
	at org.aksw.autosparql.tbsl.algorithm.learning.SimpleEntityDisambiguation.getCandidateEntities(SimpleEntityDisambiguation.java:76)
	at org.aksw.autosparql.tbsl.algorithm.learning.SimpleEntityDisambiguation.performEntityDisambiguation(SimpleEntityDisambiguation.java:48)
	at org.aksw.autosparql.tbsl.algorithm.learning.SimpleEntityDisambiguation.performEntityDisambiguation(SimpleEntityDisambiguation.java:38)
	at org.aksw.autosparql.tbsl.algorithm.learning.TBSL.answerQuestion(TBSL.java:183)
	at org.aksw.autosparql.tbsl.algorithm.learning.TBSL.answerQuestion(TBSL.java:156)
	at org.aksw.openqa.component.answerformulation.interpreter.impl.Main.main(Main.java:26)

When I posted the same in OpenQA the Repoowner suggested to take it up with AutoSPARQL forum.
Please help me in solving this issue.

**Comment by songliuchen** [comment]
i have the same problem

at org.apache.solr.client.solrj.impl.HttpSolrServer.executeMethod(HttpSolrServer.java:512)
        at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:210)
        at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:206)
        at org.apache.solr.client.solrj.request.QueryRequest.process(QueryRequest.java:91)
        at org.apache.solr.client.solrj.SolrServer.query(SolrServer.java:301)
        at org.aksw.rdfindex.SOLRIndex.getResourcesWithScores(SOLRIndex.java:82)
        at org.aksw.autosparql.commons.search.FilteredIndex.getResourcesWithScores(FilteredIndex.java:18)
        at org.aksw.autosparql.tbsl.algorithm.learning.SimpleEntityDisambiguation.getCandidateEntities(SimpleEntityDisambiguation.java:76)
        at org.aksw.autosparql.tbsl.algorithm.learning.SimpleEntityDisambiguation.performEntityDisambiguation(SimpleEntityDisambiguation.java:48)
        at org.aksw.autosparql.tbsl.algorithm.learning.SimpleEntityDisambiguation.performEntityDisambiguation(SimpleEntityDisambiguation.java:38)
        at org.aksw.autosparql.tbsl.algorithm.learning.TBSL.answerQuestion(TBSL.java:183)
        at org.aksw.autosparql.tbsl.algorithm.learning.TBSL.answerQuestion(TBSL.java:156)
        at org.aksw.autosparql.tbsl.gui.vaadin.TBSLManager.answerQuestion(TBSLManager.java:340)
        at org.aksw.autosparql.tbsl.gui.vaadin.view.MainView$11.run(MainView.java:504)
        at java.lang.Thread.run(Thread.java:745)

**Comment by KonradHoeffner** [comment]
That SOLR Server does not exist anymore, you need to set up your own. However there will probably be further problems, as we don't maintain the project anymore.
